name: mundose-pin1

services:
  jenkins:
    image: docker.io/mguazzardo/pipe-seg
    # image: jenkins/jenkins:lts-jdk21
    # image: jenkins/jenkins:alpine
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./:/app
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-network

  # jenkins-runner:
  #   # image: jenkins/jnlp-agent-docker
  #   image: jenkins/jenkins:alpine
  #   # ports:
  #   #   - "8080:8080"
  #   # volumes:
  #   #   - /var/run/docker.sock:/var/run/docker.sock
  #   networks:
  #     - jenkins-network

  registry:
    image: registry:2
    ports:
      - "5000:5000"
    networks:
      - jenkins-network

volumes:
  jenkins_data:

networks:
  jenkins-network:
